# Generated by Django 3.2.16 on 2023-05-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSocialLogin',
        ),
    ]
