# Generated by Django 3.2.16 on 2023-05-13 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_auth', '0002_delete_usersociallogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('social_signin', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, max_length=64, null=True)),
                ('provider_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
