# Generated by Django 3.2.16 on 2023-01-11 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField(default=12)),
                ('height', models.IntegerField(default=12)),
                ('cells', models.TextField(max_length=625)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_creator', to=settings.AUTH_USER_MODEL)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='builder.grid')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(blank=True, default='', max_length=50)),
                ('orientation', models.CharField(choices=[('AC', 'Across'), ('DN', 'Down')], default='AC', max_length=2)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_words', to='builder.puzzle')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_words', to='builder.dictionaryword')),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(max_length=1024)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='builder.dictionaryword')),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_string', models.CharField(max_length=200)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='builder.dictionaryword')),
            ],
        ),
    ]
