# Generated by Django 3.2.16 on 2023-01-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryword',
            name='string',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
