# Generated by Django 3.2.16 on 2023-01-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_alter_dictionaryword_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryword',
            name='string',
            field=models.CharField(max_length=100),
        ),
    ]
