# Generated by Django 3.2.16 on 2023-04-04 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0003_alter_dictionaryword_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrosswordClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.CharField(max_length=1024)),
                ('solution', models.CharField(max_length=127)),
                ('word_lengths', models.CharField(max_length=64)),
                ('orientation', models.CharField(choices=[('AC', 'Across'), ('DN', 'Down')], default='AC', max_length=2)),
                ('start_row', models.IntegerField()),
                ('start_col', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrosswordPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_creator', to=settings.AUTH_USER_MODEL)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='builder.grid')),
            ],
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='grid',
        ),
        migrations.RemoveField(
            model_name='puzzleword',
            name='puzzle',
        ),
        migrations.RemoveField(
            model_name='puzzleword',
            name='word',
        ),
        migrations.DeleteModel(
            name='Clue',
        ),
        migrations.DeleteModel(
            name='Puzzle',
        ),
        migrations.DeleteModel(
            name='PuzzleWord',
        ),
        migrations.AddField(
            model_name='crosswordclue',
            name='puzzle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clues', to='builder.crosswordpuzzle'),
        ),
    ]
