# Generated by Django 3.2.16 on 2023-04-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_auto_20230404_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswordclue',
            name='clue',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='crosswordclue',
            name='start_col',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crosswordclue',
            name='start_row',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crosswordclue',
            name='word_lengths',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
