# Generated by Django 3.2.16 on 2023-04-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_auto_20230404_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswordpuzzle',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
