# Generated by Django 3.2.16 on 2023-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_crosswordpuzzle_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswordclue',
            name='clue_number',
            field=models.IntegerField(default=0),
        ),
    ]
