# Generated by Django 3.2.16 on 2023-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_crosswordclue_clue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswordpuzzle',
            name='last_editied',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
