# Generated by Django 3.2.16 on 2023-04-22 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_rename_last_editied_crosswordpuzzle_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswordpuzzle',
            name='grid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='builder.grid'),
        ),
    ]
