# Generated by Django 3.2.16 on 2023-05-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_alter_crosswordpuzzle_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswordpuzzle',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crosswordpuzzle',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
