# Generated by Django 3.2.16 on 2023-05-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0013_alter_crosswordclue_puzzle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswordclue',
            name='puzzle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='builder.crosswordpuzzle'),
        ),
    ]
