# Generated by Django 3.2.16 on 2023-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_alter_crosswordclue_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswordpuzzle',
            name='puzzle_type',
            field=models.CharField(choices=[('CSWD', 'Crossword'), ('CRGM', 'Crannagram')], default='CSWD', max_length=4),
        ),
    ]
